version: "2"

services:
  go-authen:
    build:
      context: ../
      dockerfile: ./build/docker/Dockerfile
    volumes:
      - ../:/app
    working_dir: /app
    image: go-authen
    environment:
      - MYSQL_HOST=appdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - "8081:8080"
    depends_on:
      - appdb
      - redis

  appdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5.0.2-alpine
    ports:
      - "6379:6379"
